name: Random Replica CI/CD

on:
  push:
    paths:
      - "examples/random-replica/**"
      - ".github/workflows/example-ci.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: ${{ secrets.REGISTRY_USERNAME }}/random-replica
          dockerfile: example/random-replica/Dockerfile
          directory: example/random-replica
          registry: docker.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
